### ISSUE TITLE
Cuda error occured, while launching a small-scale baseline

### ISSUE THREAD

**Issue by lkm2835** [facebookresearch/metaseq#90]
## 🐛 Bug

I tried launching a small-scale baseline.
But, error occured (CUDA error: an illegal memory access was encountered)

### To Reproduce

Launching a small-scale baseline run
```
base_dir=`pwd`
export CUDA_HOME='/usr/local/cuda'

opt-baselines \
  -g 2 -t 1 \
  -p test_v0 \
  --model-size 125m \
  --data /w/kyungmin/data \
  --azure \
  --checkpoints-dir /w/kyungmin/metaseq \
  --no-tensorboard \
  --no-wandb \
  --local
```

Error message
```
2022-05-11 06:20:16 | INFO | metaseq.utils | ***********************CUDA enviroments for all 1 workers***********************
2022-05-11 06:20:16 | INFO | metaseq.utils | rank   0: capabilities =  8.0  ; total memory = 39.586 GB ; name = NVIDIA A100-SXM4-40GB                   
2022-05-11 06:20:16 | INFO | metaseq.utils | ***********************CUDA enviroments for all 1 workers***********************
2022-05-11 06:20:16 | INFO | metaseq_cli.train | training on 2 devices (GPUs/TPUs)
2022-05-11 06:20:16 | INFO | metaseq_cli.train | max tokens per GPU = None and batch size per GPU = 256
2022-05-11 06:20:17 | WARNING | metaseq.checkpoint_utils | Proceeding without metaseq-internal installed! Please check if you need this!
2022-05-11 06:20:17 | INFO | metaseq_cli.train | nvidia-smi stats: {'gpu_0_mem_used_gb': 5.3076171875, 'gpu_1_mem_used_gb': 5.2060546875, 'gpu_2_mem_used_gb': 2.216796875, 'gpu_3_mem_used_gb': 2.216796875, 'gpu_4_mem_used_gb': 0.0068359375, 'gpu_5_mem_used_gb': 0.0068359375, 'gpu_6_mem_used_gb': 0.0068359375, 'gpu_7_mem_used_gb': 0.0068359375, 'gpu_8_mem_used_gb': 0.0068359375, 'gpu_9_mem_used_gb': 0.0068359375, 'gpu_10_mem_used_gb': 0.0068359375, 'gpu_11_mem_used_gb': 0.0068359375, 'gpu_12_mem_used_gb': 0.0068359375, 'gpu_13_mem_used_gb': 0.0068359375, 'gpu_14_mem_used_gb': 0.0068359375, 'gpu_15_mem_used_gb': 0.0068359375}
2022-05-11 06:20:17 | WARNING | metaseq.checkpoint_utils | Proceeding without metaseq-internal installed! Please check if you need this!
2022-05-11 06:20:17 | INFO | metaseq.checkpoint_utils | attempting to load checkpoint from: /w/kyungmin/metaseq/test_v0.bm_none.gpt2.me_fp16.fsdp.zero2.relu.transformer_lm_megatron.nlay12.emb768.lrnpos.0emb_scale.tps2048.adam.b2_0.95.eps1e-08.cl1.0.lr0.0006.endlr6e-05.wu715.dr0.1.atdr0.1.0emb_dr.wd0.1.ms256.uf1.mu572204.s1.ngpu2/checkpoint_last-model_part-0-shard0.pt
2022-05-11 06:20:17 | INFO | metaseq.trainer | No existing checkpoint found /w/kyungmin/metaseq/test_v0.bm_none.gpt2.me_fp16.fsdp.zero2.relu.transformer_lm_megatron.nlay12.emb768.lrnpos.0emb_scale.tps2048.adam.b2_0.95.eps1e-08.cl1.0.lr0.0006.endlr6e-05.wu715.dr0.1.atdr0.1.0emb_dr.wd0.1.ms256.uf1.mu572204.s1.ngpu2/checkpoint_last-model_part-0-shard0.pt
2022-05-11 06:20:17 | INFO | metaseq.trainer | loading train data for epoch 1
2022-05-11 06:20:17 | INFO | metaseq.tasks.streaming_language_modeling | setting shuffle buffer size to 2560
2022-05-11 06:20:18 | INFO | metaseq.trainer | begin training epoch 1
2022-05-11 06:20:18 | INFO | metaseq_cli.train | Start iterating over samples
THCudaCheck FAIL file=../aten/src/THC/THCCachingHostAllocator.cpp line=280 error=700 : an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/kyungmin.lee/Megatron-LM/megatron/mpu/random.py", line 166, in fork
    yield
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T15_19_56.042263/metaseq/model_parallel/modules/multihead_attention.py", line 375, in forward
    attn_probs = self.dropout_module(attn_probs)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T15_19_56.042263/metaseq/modules/dropout.py", line 26, in forward
    return F.dropout(x, p=self.p, training=True, inplace=inplace)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/functional.py", line 1169, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:
```

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq_cli/train.py", line 591, in <module>
    cli_main()
  File "./slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq_cli/train.py", line 587, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/distributed/utils.py", line 256, in call_main
    return _spawn_helper(main, cfg, kwargs)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/distributed/utils.py", line 234, in _spawn_helper
    retval = distributed_main(-1, main, cfg, kwargs)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/distributed/utils.py", line 203, in distributed_main
    main(cfg, **kwargs)
  File "./slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq_cli/train.py", line 167, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "./slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq_cli/train.py", line 322, in train
    valid_losses, should_stop = train(i, samples)
  File "./slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq_cli/train.py", line 282, in train
    log_output = trainer.train_step(samples)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/trainer.py", line 721, in train_step
    raise e
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/trainer.py", line 689, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/tasks/base_task.py", line 409, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/model_parallel/criterions/vocab_parallel_cross_entropy.py", line 43, in forward
    net_output = model(**sample["net_input"])
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyungmin.lee/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 1152, in forward
    outputs = self.module(*args, **kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyungmin.lee/fairscale/fairscale/nn/misc/flatten_params_wrapper.py", line 459, in forward
    return self.module(*inputs, **kwinputs)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/models/base_model.py", line 371, in forward
    return self.decoder(src_tokens, **kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/models/transformer.py", line 639, in forward
    x, extra = self.extract_features(
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/models/transformer.py", line 664, in extract_features
    return self.extract_features_scriptable(
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/models/transformer.py", line 728, in extract_features_scriptable
    x, layer_attn, _, l_aux_i = layer(
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyungmin.lee/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 1152, in forward
    outputs = self.module(*args, **kwargs)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyungmin.lee/fairscale/fairscale/nn/misc/flatten_params_wrapper.py", line 459, in forward
    return self.module(*inputs, **kwinputs)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/modules/checkpoint_activation_wrapper/checkpoint_activations.py", line 207, in _checkpointed_forward
    output = CheckpointFunction.apply(
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/modules/checkpoint_activation_wrapper/checkpoint_activations.py", line 307, in forward
    outputs = run_function(*unpacked_args, **unpacked_kwargs)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/modules/transformer_layer.py", line 509, in forward
    x, attn = self.forward_attention(
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/model_parallel/modules/transformer_layer.py", line 163, in forward_attention
    (attn_output, attn_bias), attn_weights = self.self_attn(
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kyungmin.lee/metaseq/slurm_snapshot_code_oss/2022-05-11T18_58_51.281777/metaseq/model_parallel/modules/multihead_attention.py", line 375, in forward
    attn_probs = self.dropout_module(attn_probs)
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kyungmin.lee/Megatron-LM/megatron/mpu/random.py", line 169, in fork
    self.states_[name] = torch.cuda.get_rng_state()
  File "/home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/cuda/random.py", line 31, in get_rng_state
    return default_generator.get_state()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
terminate called after throwing an instance of 'c10::Error'
  what():  NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:181, unhandled cuda error, NCCL version 21.0.3
Process Group destroyed on rank 0
Exception raised from ncclCommAbort at ../torch/csrc/distributed/c10d/NCCLUtils.hpp:181 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fa6d3bd2d62 in /home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7fa6d3bcf68b in /home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x30a768e (0x7fa730eab68e in /home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #3: c10d::ProcessGroupNCCL::~ProcessGroupNCCL() + 0x113 (0x7fa730e94233 in /home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #4: c10d::ProcessGroupNCCL::~ProcessGroupNCCL() + 0x9 (0x7fa730e94459 in /home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #5: <unknown function> + 0xe6e6b6 (0x7fa79b1746b6 in /home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0xe543c5 (0x7fa79b15a3c5 in /home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x2a3790 (0x7fa79a5a9790 in /home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x2a49fe (0x7fa79a5aa9fe in /home/kyungmin.lee/anaconda3/envs/large/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #19: __libc_start_main + 0xf3 (0x7fa7a2d750b3 in /lib/x86_64-linux-gnu/libc.so.6)

```

### Environment

 - metaseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.10+cu113
 - OS (e.g., Linux, Windows, MacOS): Linux
 - How you installed metaseq (`pip`, source): pip3
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.4
 - GPU models and configuration: A100 / 40GB / 16 device
 - Any other relevant information:

**Comment by stephenroller** [comment]
This is a known issue with fairscale. Instead of getting an OOM exception, you get this crash. So you're running out of memory.

**Comment by lkm2835** [comment]
Thanks, it's solved by increasing gpu devices.
